name: Check

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.ref, 'refs/tags') }}

    strategy:
      fail-fast: false
      matrix:
        hatch-environment:
          - docs:build
          - test:lint
          - test:pkglint

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Install dependencies
        run: python -m pip install hatch

      - name: Run
        run: hatch run ${{ matrix.hatch-environment }}
